#!/usr/bin/env bash

echo -n "Nome do usuários: "
whoami

echo -n "Nome da máquina: "
hostname

echo -n "Tempo de atividade: "
uptime -p

echo -n "Versão do Kernel e Estrutura do Sistema: "
uname -rms

